### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by rndstr**

### CODE REVIEW

**Comment by dbu** [comment]
the bootstrapping has changed in the https://github.com/symfony-cmf/phpcrbrowser. when this pull request is merged, it must be updated to reflect that new bootstrap.

**Comment by dbu** [comment]
@rndstr can you please review if this patch still makes sense and if yes merge master into your branch and check for breakings?

**Comment by lsmith77** [comment]
@rndstr: ping

**Comment by rndstr** [comment]
Nope, master now already reads credentials from config

**Pull request closed without merging**
