### PR TITLE
Added autoloader for jackalope lib.

### PR DESCRIPTION
**Pull request by drm**
The one provided in the jackalope library depends on the Symfony autoloader component currently, which isn't included in the phpcrbrowser. The referred autoloader.php doesn't exist in the latest Jackalope, so I added a  local autoloader callback to get it running again.

Not sure if you would rather have it in inc/ or localinc/ but at least the code works :)

### CODE REVIEW

**Comment by dbu** [comment]
if you recursively update the submodules, the symfony autoloader is loaded at the place src/autoload.jackrabbit.dist.php resp. src/autoload.doctrine-dbal.dist.php are expecting it

so this is more of a documentation issue. if you want to use the browser with the dbal variant, the autoloader won't be sufficient. can you please change the pull request to make it want include 

```
'../ext/jackalope/src/autoload.php'
```

and refer to the README of jackalope how to get the right autoload.php there?

**Comment by drm** [comment]
Hm, i tried updating the submodules before, but I have everything pulled already. Also, `'../ext/jackalope/src/autoload.php'` doesn't exist in the included jackalope version (which is just HEAD of master). I'm probably missing something obvious ...?

**Comment by dbu** [comment]
i fixed the download script to initialize jackalope properly and the index.php to include the new autoload file.
if you already have the checkout, you need to run in ext/jackalope

```
git submodule update --init --recursive 
```

**Comment by drm** [comment]
ok excellent. Thanks

**Pull request closed without merging**
